### ISSUE TITLE
I used this code in my project

### ISSUE THREAD

**Issue by afroewis** [gwannon/Cyberpunk-2077-theme-css#1]
Hi gwannon, 

I was so impressed by your styles that I decided to use them in my website. Therefore, I created a Hugo theme based on your styles. You can find it here: https://github.com/afroewis/hugo-cyberpunk2077

I followed these steps:

- Used GPL v3
- Put a link to your repo in README.md
- Copied your CSS file and put a link to your repo in it

I hope that this is fine. I just wanted to check with you. 
Thanks a lot for this beautiful piece of work.

**Comment by gwannon** [comment]
It's all OK, thanks you for trusting in my work :)

**Comment by afroewis** [comment]
I'm glad to hear that. Thanks 😃
