### ISSUE TITLE
guild names not showing

### ISSUE THREAD

**Issue by prun3** [gwannon/Cyberpunk-2077-theme-css#2]
when hovering over guilds you can still see the usual name popout, but its just one solid color. 
Im not sure if the rgb code for text is the same as guild popout but its really my only guess as emotes in a guild-name still show on the popout. 

(barely ever used github b4 so sorry if im doing something wrong or submitted on a wrong forum.)

**Comment by gwannon** [comment]
Sorry, i don't understand you. Can you send a screenshoot of the problem? :)

**Comment by prun3** [comment]
![image](https://user-images.githubusercontent.com/70281012/135097118-185edb0a-7309-4a6f-a6cd-a6ca06771649.png)

not sure if this works but if it does you can see the popout which is supposed to identify the server.  ty for the fast response time thou <3

**Comment by gwannon** [comment]
Sorry, but I think that your problem is not relates to this repository. This is only a CSS theme to use in a website.
