### ISSUE TITLE
Vertical section

### ISSUE THREAD

**Issue by Q300Z** [gwannon/Cyberpunk-2077-theme-css#3]
Have the same style as the horizontal sections but vertical

**Comment by gwannon** [comment]
Sorry, but I don't understand you. You mean this? Do you mean put the transitions between sections on the left and right instead of above and below?

**Comment by Q300Z** [comment]
yes !

**Comment by gwannon** [comment]
I have to redesign the left and right border of the section but you can see the effect in https://codepen.io/gwannon/pen/LYjvOLK

**Comment by gwannon** [comment]
New lateral borders for section using the class .both
